# Generated by Django 4.0.6 on 2022-08-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name_plural': 'Recipients'},
        ),
        migrations.AddField(
            model_name='recipient',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
